### ISSUE TITLE
MPS-Contrib license

### ISSUE THREAD

**Issue by mkolodziejskiEP** [JetBrains/MPS-Contrib#1]
How is the code in this repository licensed? Is it published under the same conditions as MPS, which is licensed under the Apache 2.0 License (according to this link: https://www.jetbrains.com/mps/download/license.html)? I can't find any license file in the repo.

**Comment by vaclav** [comment]
The code has been taken from the MPS sources, so the same licence applies to the MPS-Contrib project.

**Comment by vaclav** [comment]
Do you have any specific plans with the Contrib library? We have not spent much time maintaining it recently.

**Comment by mkolodziejskiEP** [comment]
Thank you for clarification.
As for now, we're just evaluating if this code is suitable for us. Licensing issue was a blocker, but it's clear now. No worries about lack of active support on your side.
